spring:
  profiles: dev
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true
  cloud:
      gateway:
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
              exposedHeaders: "x-total-count"
              allowCredentials: true
        discovery:
           locator:
              #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，# 这个router将以服务名开头的请求路径转发到对应的服务
              enabled: true
              #将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了,比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上
              lowerCaseServiceId: true
#        routes:
#        - id: user
#          uri: lb://USER
#          order: 0
#          predicates:
#          - Path=/user/**
#          filters:
#          - RewritePath=/user/(?<segment>.*), /$\{segment}     
server:
  port: 8011

management:
  server:
    port: 9011

logging:
  file: "${LOG_HOME :D:/logs}/boot/${spring.profiles}/${spring.application.name}.log"
  level:
    org: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       defaultZone: http://localhost:8077/eureka/