server:
  port: 8077                    # 指定该Eureka实例的端口

management:
  server:
    port: 9077

logging:
  file: "${LOG_HOME :D:/logs}/boot/${spring.profiles}/${spring.application.name}.log"

eureka:
  instance:
    preferIpAddress: true
  server:
     enableSelfPreservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/

spring:
  mail:
    default-encoding: UTF-8  # 字符集
    host: smtp.163.com  # 电子邮件地址
    username: holyforjobs@163.com #邮箱账号名
    password: jiu23456 #授权密码
    protocol: smtp #协议
    properties:
      set-to: 653848177@qq.com
  profiles: dev

